/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import Head from 'next/head';
import Extension from '../src';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a href="https://github.com/focusreactive/headless-cms-yaml-input">
            YAML Input!
          </a>
        </h1>
        <div>
          <Extension />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://focusreactive.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className="footer-note">Powered by</span>
          <img
            src="https://raw.githubusercontent.com/focusreactive/storybook-graphql-kit/master/docs/focusreactive-logo.svg"
            alt="FocusReactive Logo"
            width={200}
            height={60}
          />
        </a>
      </footer>
    </div>
  );
};

export default Home;
